{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mars.united.international.plugins",
    "module": "aggregation",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aggregation-1.0.1.jar",
          "url": "aggregation-1.0.1.jar",
          "size": 31001,
          "sha512": "475a8c1d435e0cc4ca0ece652b3fefc85a97577c2edc08f21c77f13217791c5787ab04cfd857d16365a0d3217f96d45fc73da1bfcb3fa8fecef6c4caff46a567",
          "sha256": "4fbeaa53b3a4bccfca4b58be266ff4fcab964b6de87e0d78b83c694d00d397be",
          "sha1": "3d2ee54ae83bed7d84f62f37dd1c00eaaeb9c5a3",
          "md5": "50e771acdcbb9f7e15a9208b02d7f292"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aggregation-1.0.1.jar",
          "url": "aggregation-1.0.1.jar",
          "size": 31001,
          "sha512": "475a8c1d435e0cc4ca0ece652b3fefc85a97577c2edc08f21c77f13217791c5787ab04cfd857d16365a0d3217f96d45fc73da1bfcb3fa8fecef6c4caff46a567",
          "sha256": "4fbeaa53b3a4bccfca4b58be266ff4fcab964b6de87e0d78b83c694d00d397be",
          "sha1": "3d2ee54ae83bed7d84f62f37dd1c00eaaeb9c5a3",
          "md5": "50e771acdcbb9f7e15a9208b02d7f292"
        }
      ]
    }
  ]
}
